spring.application.name=demo

couchdb.primary.url=http://localhost:5984
couchdb.secondary.url=http://localhost:5985
couchdb.databases=tops,bottoms,outerwear,dresses,footwear
couchdb.username=admin
couchdb.password=yourpassword
couchdb.connect-timeout-ms=3000

springdoc.swagger-ui.path=/swagger-ui.html
